site_name: Agents in Action
theme:
  name: material
nav:
  - Home: index.md
  - 7-Day Agents in Action Series:
    - Day 01 - Agents are here and they are staying: 01-agents-are-here-and-they-are-staying.md
    - Day 02 - How Agents Think: 02-how-agents-think.md
    - Day 03 - Memory - The Agent's Brain: 03-memory-the-agents-brain.md
    - Day 04 - Agentic RAG Ecosystem: 04-agentic-rag-ecosystem.md
    - Day 05 - Multimodal Agents: 05-multimodal-agents.md
    - Day 06 - Scaling Agents - Architectures with Google ADK, A2A, and MCP: 06-scaling-agents-architectures-with-google-adk-a2a-and-mcp.md
    - Day 07 - Fully Functional Agent Loop: 07-fully-functional-agent-loop.md
  - 10-Day Agents in Action Series:
    - Day 01 - From LLMs to AI Agents: day-1-from-llms-to-ai-agents.md
    - Day 02 - Building Your First AI Sales Agent: day-2-building-your-first-ai-sales-agent.md
    - Day 03 - An Agent that Builds LinkedIn Posts Directly from YouTube Videos: day-3-linkedin-to-youtube-agent.md
    - Day 04 - The Unofficial Airbnb AI Agent: day-4-the-unofficial-airbnb-ai-agent.md
    - Day 05 - Build a Sales Prospect and A Deep Research Finance Agent: day-5-sales-prospect-and-deep-research-finance-agent.md
    - Day 06 - The Ultimate AI Research Assistant: day-6-the-ultimate-ai-research-assistant.md
    - Day 07 - The Ultimate AI Finance Agent: day-7-the-ultimate-ai-finance-agent.md
    - Day 08 - The Ultimate AI Blog Post Agent: day-8-the-ultimate-ai-blog-post-agent.md
  - Context-Engineering: context-engineering.md
