site_name: Agents in Action
theme:
  name: material

nav:
  - Why we built this course: index.md
  - Introduction: introduction.md
  - Chapter 01 - From LLMs to AI Agents: from-llms-to-ai-agents.md
  - Chapter 02 - Agents are Here and They are Staying: agents-are-here-and-they-are-staying.md
  - Chapter 03 - n8n - Build Your First End-to-End Agent:
      - 3a. Introducing Lovable: lovable.md
      - 3b. Introducing n8n and Building Your First Workflow: meet-n8n.md
      - 3c. Connecting n8n and Lovable via Webhooks: lovable-webhook-n8n.md
  - Chapter 04 - Sales Agent to Find the Right Customer: sales-agent-to-find-the-right-customer.md
  - Chapter 05 - Build a Chatbot that Knows Your Documents: chatbot-that-knows-your-docs.md
  - Chapter 06 - Build Your Own Perplexity Clone: your-own-perplexity-clone.md
  - Chapter 07 - Teach Your RAG Agent to Remember: supabase-rag-with-memory.md
  - Chapter 08 - Give Your Book A Voice - The AI Assisted Edition: book-companion-voice-rag-agent.md
  - Chapter 09 - Automate Your Content - YouTube to LinkedIn Agent: youtube-to-linkedin-agent.md
  - Chapter 10 - The Unofficial AirBnb AI Agent: the-unofficial-airbnb-ai-agent.md
  - Chapter 11 - LinkedIn Human in the Loop Agent: linkedin-post-human-in-the-loop.md
  - Chapter 12 - The Ultimate AI Blog Post Agent: the-ultimate-ai-blog-post-agent.md
  - Chapter 13 - Fully Functional Agent Loop - Travel-Agent: travel-agent.md
  - Chapter 14 - Intelligent Research - The Ultimate AI Research Assistant: the-ultimate-ai-research-assistant.md
  - Chapter 15 - Investment Intelligence - The Ultimate AI Finance Agent: the-ultimate-ai-finance-agent.md
  - Chapter 16 - Agent that Creates Other Agents: workflow-creator.md
